//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Inv3D.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_Inv3DTYPE                   129
#define IDD_COLOR_GRAD                  130
#define ID_MODEL_DEFINE                 132
#define ID_MODEL_INVERT                 133
#define IDD_DLG_DEFINE_MODEL            134
#define IDD_DLG_FORWARD_MODEL           135
#define IDD_DLG_INVERT                  136
#define ID_MODEL_IMPORT                 137
#define ID_EDIT_COLORS                  138
#define ID_MODEL_NEXT                   141
#define ID_MODEL_PREVIOUS               142
#define ID_MODEL_FIRST                  143
#define ID_MODEL_LAST                   144
#define ID_VIEW_SHOWTEXT                145
#define ID_MODEL_IMPORT_APPEND          146
#define ID_VIEW_SHOW_VOXELS             147
#define ID_VIEW_SHOW_SLICES             148
#define ID_VIEW_SLICE_NEW               149
#define IDD_DIALOG1                     150
#define IDD_DLG_SLICE                   150
#define ID_EDIT_SLICES                  151
#define IDD_DLG_SLICE_MANAGER           152
#define ID_VIEW_SLICE_NEXT              153
#define ID_VIEW_SLICE_PREVIOUS          154
#define ID_VIEW_TRESHOLD_APPLY          155
#define ID_VIEW_SLICE_NEXT_ACTIVATE     156
#define ID_VIEW_SLICE_PREVIOUS_ACTIVATE 157
#define IDD_GRID_PROPERTIES             158
#define ID_EDIT_FIELD                   159
#define ID_VIEW_SHOW_FIELD              160
#define ID_MODEL_LOAD_FOWARD            161
#define ID_MODEL_SAVE_FORWARD           162
#define IDD_DLG_PENAL                   163
#define IDC_MOD_TYPE                    1000
#define IDC_MOD_TYPE_3D                 1001
#define IDC_MODEL_NAME                  1002
#define IDC_ADD_PEG                     1002
#define IDC_BROWSE_MODEL_NAME           1003
#define IDC_NX                          1004
#define IDC_NEWPEG_POSITION             1004
#define IDC_X0                          1005
#define IDC_NEWPEG_COLOUR               1005
#define IDC_XCS                         1006
#define IDC_SELPEG_POSITION             1006
#define IDC_NY                          1007
#define IDC_SELPEG_COLOUR               1007
#define IDC_Y0                          1008
#define IDC_SELPEG                      1008
#define IDC_YCS                         1009
#define IDC_NZ                          1010
#define IDC_Z0                          1011
#define IDC_ZCS                         1012
#define IDC_DEL_PEG                     1012
#define IDC_X_MIN                       1013
#define IDC_FORWARD_MODEL               1013
#define IDC_Y_MIN                       1014
#define IDC_PENALIZATION                1014
#define IDC_Z_MIN                       1015
#define IDC_EDIT_TRESHOLD               1015
#define IDC_X_MAX                       1016
#define IDC_Y_MAX                       1017
#define IDC_COMBO_FOCUSING              1017
#define IDC_Z_MAX                       1018
#define IDC_COMBO_ROWS                  1018
#define IDC_SET_MODEL                   1019
#define IDC_COMBO_COLS                  1019
#define IDC_PROFILE                     1019
#define IDC_MOD_VAL                     1020
#define IDC_GRADIENT                    1020
#define IDC_ALPHA                       1020
#define IDC_INIT_MOD                    1021
#define IDC_TYPE                        1021
#define IDC_PEN_MAX                     1021
#define IDC_CREATE_MODEL                1022
#define IDC_RADIO2                      1022
#define IDC_LIST                        1022
#define IDC_TEMP_DIR                    1023
#define IDC_METHOD_COMBO                1023
#define IDC_RADIO3                      1023
#define IDC_PROPERTIES                  1023
#define IDC_BROWSE_TEMP_DIR             1024
#define IDC_ADD                         1024
#define IDC_CREATE_FRW_MODEL            1025
#define IDC_DELETE                      1025
#define IDC_ITER_FCS                    1026
#define IDC_CURRENT                     1026
#define IDC_ITER_CG                     1027
#define IDC_CG_EPS                      1028
#define IDC_MEM_TOTAL                   1029
#define IDC_STR_FOCUSING                1029
#define IDC_DISK_MATRIX                 1030
#define IDC_MODEL_LOAD                  1030
#define IDC_MODEL_PTS                   1031
#define IDC_SHOWTOOLTIPS                1031
#define IDC_STR_CG                      1031
#define IDC_MEM_MODEL                   1032
#define IDC_STR_RESIDUAL                1032
#define IDC_INVERT_TYPE                 1032
#define IDC_MEM_MATRIX                  1033
#define IDC_EDIT4                       1033
#define IDC_INV_REGULARIZED             1033
#define IDC_MEM_DATA                    1034
#define IDC_EDIT5                       1034
#define IDC_INVERT_NORMAL               1034
#define IDC_BROWSE_MEASUREMENTS         1035
#define IDC_FOCUSING_MODEL_SAVE         1035
#define IDC_MEM_OTHER                   1036
#define IDC_MATRIX_SHRINK               1036
#define IDC_ADD_NOISE                   1037
#define IDC_BUTTON2                     1037
#define IDC_MODEL_SAVE                  1037
#define IDC_INVERT_PRECOND_DIAG         1037
#define IDC_PROGRESS_FOCUS              1038
#define IDC_PROGRESS_CG                 1039
#define IDC_INVERT                      1040
#define IDC_STR_PROGRESS                1041
#define IDC_STR_INIT                    1041
#define IDC_PTS_X                       1042
#define IDC_PROGRESS_INIT               1042
#define IDC_PTS_Y                       1043
#define IDC_PTS_ELEV                    1044
#define IDC_DLGINV_OPACITY              1044
#define IDC_PTS_NOISE                   1045
#define IDC_DLGINV_OPACITY_SET          1045
#define IDC_MODEL_PTS2                  1046
#define IDC_MODEL_MATRIX                1046
#define IDC_BROWSE_MATRIX               1047
#define IDC_CG_RESTART                  1048
#define IDC_MODEL_PENAL                 1048
#define IDC_REG_MIU                     1049
#define IDC_MIN_X                       1049
#define IDC_BROWSE_PENAL                1049
#define IDC_MAX_X                       1050
#define IDC_MIN_Y                       1051
#define IDC_PEN_MIN                     1051
#define IDC_MAX_Y                       1052
#define IDC_SET_PENVAL                  1052
#define IDC_MOD_GRAVITY                 1053
#define IDC_WHOLE_MODEL                 1053
#define IDC_MOD_MAGNETICS               1054
#define IDC_TRANSP_ALPHA                1054
#define IDC_PENAL_MIN                   1055
#define IDC_TRANSP_COLOR                1055
#define IDC_EDIT1                       1055
#define IDC_MODEL_GRID                  1055
#define IDC_PENAL_MAX                   1056
#define IDC_BROWSE_MODEL                1056
#define IDC_FCS_POW                     1058
#define IDC_MODEL_START                 1059
#define IDC_SAVE                        1307
#define IDC_BROWSE                      1307
#define IDC_NAME                        1313
#define IDC_CUSTOM_ENABLE               1345
#define IDC_HST_EQ                      1401
#define IDC_MIN_Z                       1408
#define IDC_CS_X                        1429
#define IDC_MAX_Z                       1431
#define IDC_CS_Y                        1432
#define IDC_FILE_PATH                   1434
#define IDC_COLOR_TABLE                 1435
#define IDC_LOAD                        1441
#define IDC_VALUE                       1455
#define IDC_CUSTOM_MAX                  1457
#define IDC_CUSTOM_MIN                  1458
#define ID_BUTTON32796                  32796

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        164
#define _APS_NEXT_COMMAND_VALUE         32800
#define _APS_NEXT_CONTROL_VALUE         1057
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
